import type { Metadata } from "next";
//import { Inter } from "next/font/google";

import { Header } from "./components/common";
import { Footer } from "./components/common";
import AuthProviders from "./components/providers/AuthProviders";
import "./globals.css";
import { GlobalStateProvider } from "./components/providers/GlobalStateProvider";

//const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={''}>
        <AuthProviders>
          <GlobalStateProvider>
            <Header/>
              { children }
            <Footer/>
          </GlobalStateProvider>
        </AuthProviders>
      </body>
    </html>
  );
}
